[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
store = { path = "../store" }
anyhow = "1.0"
bevy = { version = "0.12.1", features = ["jpeg"] }
renet = "0.0.9"
bevy_renet = "0.0.10"
bincode="1.3.1"