[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
store = { path = "../store" }
serde = { version = "1", features = ["derive"] }
bincode = "1.3.1"
renet = "0.0.16"
log = "0.4"
env_logger="0.11.5"
local-ip-address = "0.6"